# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expiration',
            old_name='end_date',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='expiration',
            old_name='start_date',
            new_name='open_date',
        ),
    ]
