# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiration', '0003_auto_20180111_0302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Period',
            new_name='Expiration',
        ),
        migrations.AlterModelOptions(
            name='expiration',
            options={'ordering': ['month'], 'verbose_name': 'expiration', 'verbose_name_plural': 'expirations'},
        ),
        migrations.AlterModelTable(
            name='expiration',
            table='expiration',
        ),
    ]
