# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('diff', models.IntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change(%)')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', unique_for_date='date')),
            ],
            options={
                'verbose_name': 'day',
                'db_table': 'stock_day',
                'verbose_name_plural': 'days',
                'ordering': ['date'],
            },
        ),
    ]
