# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180130_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.PositiveIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)')),
                ('fix', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', unique_for_date='date')),
            ],
            options={
                'verbose_name_plural': 'cycles',
                'verbose_name': 'cycle',
                'db_table': 'stock_cycle',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', unique_for_date='date')),
            ],
            options={
                'verbose_name_plural': 'expirations',
                'verbose_name': 'expiration',
                'db_table': 'stock_expiration',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', unique_for_date='date')),
            ],
            options={
                'verbose_name_plural': 'months',
                'verbose_name': 'month',
                'db_table': 'stock_month',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='day',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)'),
        ),
    ]
