# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('market', models.BooleanField(default=False)),
                ('future', models.BooleanField(default=False)),
                ('option', models.BooleanField(default=False)),
                ('fund', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'index_item',
            },
        ),
    ]
