# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='future',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.BooleanField(default=False),
        ),
    ]
