# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
