# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_item_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
