# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171220_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='market',
            field=models.BooleanField(default=False),
        ),
    ]
