# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20171223_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=6)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
            ],
            options={
                'db_table': 'index_calendar_month',
            },
        ),
        migrations.CreateModel(
            name='SettlementMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=6)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
            ],
            options={
                'db_table': 'index_settlement_month',
            },
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Index',
        ),
        migrations.AlterModelTable(
            name='index',
            table='index',
        ),
        migrations.AddField(
            model_name='settlementmonth',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
        migrations.AddField(
            model_name='calendarmonth',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
    ]
