# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20171228_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=7)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'db_table': 'index_calendar_month',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=7)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'db_table': 'index_day',
            },
        ),
        migrations.CreateModel(
            name='SettlementMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=7)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'db_table': 'index_settlement_month',
            },
        ),
        migrations.RemoveField(
            model_name='calendarmonthly',
            name='index',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='index',
        ),
        migrations.RemoveField(
            model_name='settlementmonthly',
            name='index',
        ),
        migrations.DeleteModel(
            name='CalendarMonthly',
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
        migrations.DeleteModel(
            name='SettlementMonthly',
        ),
    ]
