# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20171228_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwelveReversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=7)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='change (%)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'db_table': 'index_twelve_reversal',
            },
        ),
    ]
