# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_twelvereversal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarMonth',
            new_name='Month',
        ),
        migrations.RenameModel(
            old_name='TwelveReversal',
            new_name='Reversal',
        ),
        migrations.RenameModel(
            old_name='SettlementMonth',
            new_name='Settlement',
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'day', 'verbose_name_plural': 'days'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'index', 'verbose_name_plural': 'indices'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'month', 'verbose_name_plural': 'months'},
        ),
        migrations.AlterModelOptions(
            name='reversal',
            options={'verbose_name': 'reversal', 'verbose_name_plural': 'reversals'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'settlement', 'verbose_name_plural': 'settlements'},
        ),
        migrations.AlterModelTable(
            name='month',
            table='index_month',
        ),
        migrations.AlterModelTable(
            name='reversal',
            table='index_reversal',
        ),
        migrations.AlterModelTable(
            name='settlement',
            table='index_settlement',
        ),
    ]
