# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20171230_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
        migrations.AlterField(
            model_name='month',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
        migrations.AlterField(
            model_name='reversal',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index'),
        ),
    ]
