# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20171230_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
