# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_index_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about',
            field=models.TextField(),
        ),
    ]
