# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20171231_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index', unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='month',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index', unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='reversal',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index', unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='index',
            field=models.ForeignKey(db_column='index_code', on_delete=django.db.models.deletion.CASCADE, to='index.Index', unique_for_date='date'),
        ),
    ]
