# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20180108_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='about',
        ),
    ]
