# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_index_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='difference',
            new_name='diff',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='difference',
            new_name='diff',
        ),
        migrations.RenameField(
            model_name='expiration',
            old_name='difference',
            new_name='diff',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='difference',
            new_name='diff',
        ),
    ]
