# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20180110_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['date'], 'verbose_name': 'cycle', 'verbose_name_plural': 'cycles'},
        ),
        migrations.AddField(
            model_name='cycle',
            name='fix',
            field=models.BooleanField(default=False),
        ),
    ]
