# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20180112_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='fund',
            new_name='etf',
        ),
    ]
