# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180113_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['name'], 'verbose_name': 'index', 'verbose_name_plural': 'indices'},
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='base',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='diff',
        ),
    ]
