# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20180116_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiration',
            name='base',
        ),
        migrations.RemoveField(
            model_name='expiration',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='month',
            name='base',
        ),
        migrations.RemoveField(
            model_name='month',
            name='diff',
        ),
    ]
