# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_remove_day_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='sector',
            field=models.BooleanField(default=False),
        ),
    ]
