# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_index_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='market',
        ),
        migrations.RemoveField(
            model_name='index',
            name='sector',
        ),
    ]
