# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20180117_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['code'], 'verbose_name': 'index', 'verbose_name_plural': 'indices'},
        ),
        migrations.AddField(
            model_name='index',
            name='type',
            field=models.CharField(choices=[('UN', 'Unknown'), ('CO', 'Composite'), ('BL', 'Bluechip'), ('SE', 'Sector'), ('TH', 'Thematics')], default='UN', max_length=2),
        ),
    ]
