# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_remove_index_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='country',
            field=models.CharField(choices=[('미국', '미국'), ('중국', '중국'), ('일본', '일본'), ('한국', '한국')], default='한국', max_length=2),
        ),
        migrations.AddField(
            model_name='index',
            name='type',
            field=models.CharField(choices=[('미정', '미정'), ('종합', '종합'), ('대표', '대표'), ('업종', '업종'), ('테마', '테마')], default='미정', max_length=2),
        ),
    ]
