# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20180117_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='country',
            field=models.CharField(choices=[('한국', '한국'), ('미국', '미국'), ('중국', '중국'), ('일본', '일본')], default='한국', max_length=2),
        ),
    ]
