# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20180127_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)'),
        ),
        migrations.AlterField(
            model_name='day',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)'),
        ),
        migrations.AlterField(
            model_name='expiration',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)'),
        ),
        migrations.AlterField(
            model_name='month',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='change(%)'),
        ),
    ]
