# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20180131_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='fix',
            new_name='certainty',
        ),
    ]
